version: '3'

services:
  postgres:
    image: postgres:13.9
    container_name: postgres
    healthcheck:
      test: pg_isready -U admin -d users
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    volumes:
      - ./.out/pgdata:/var/lib/postgresql/data
