version: '3'

services:
  db:
    image: postgres:latest
    container_name: postgres
    healthcheck:
      test: pg_isready -U postgres -d users
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users
    volumes:
      - ./.out/pgdata:/var/lib/postgresql/data
