fork: 'prater'
depositOutputPath: ./data
initiatorPrivKey: ./keys/example.encrypted.initiator.json
initiatorPrivKeyPassword: ./keys/example.password.initiator.txt
keysharesOutputPath: ./data
operatorsInfoPath: ./data/operators.json