name: Push
on:
  push:
    branches: [feature/users-cdk]

env:
  PROJECT: casimir
  STAGE: featureuserscdk
  AWS_REGION: us-east-2

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    # Skip any pushes with commit flag '(skip deploy)'
    # Comment out for testing
    if: ${{ !contains(github.event.head_commit.message, '(skip deploy)') }}

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Install action dependencies
        run: |
          curl -sSf https://atlasgo.sh | sh

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
          
      - name: Install and build all package dependencies
        run: npm ci
        env:
          PUBLIC_STAGE: ${{ env.STAGE }}

      - name: Deploy cdk infrastructure
        run: npm run deploy:cdk

      - name: Migrate users database
        run: npm run migrations:users